# Generated by Django 3.1.7 on 2022-01-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stockquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
