# Generated by Django 3.1.7 on 2022-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockprice',
            field=models.IntegerField(default=-1),
        ),
    ]
