# Generated by Django 3.1.7 on 2022-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220129_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='accept',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
